basePath: /
definitions:
  rest.ErrorResponse:
    properties:
      message:
        example: object not found
        type: string
    type: object
  rest.MessageResponse:
    properties:
      message:
        example: success
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: demid.shumakher@gmail.com
    name: Creator
  description: This is a educational project for vk
  title: User segment service
  version: "1.0"
paths:
  /segments:
    get:
      consumes:
      - application/json
      description: get all segments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: List segments
      tags:
      - segments
  /segments/{segment}:
    delete:
      consumes:
      - application/json
      description: delete segment
      parameters:
      - description: segment name
        in: path
        name: segment
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Delete segment
      tags:
      - segments
    post:
      consumes:
      - application/json
      description: create a new segment
      parameters:
      - description: segment name
        in: path
        name: segment
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Create segment
      tags:
      - segments
    put:
      consumes:
      - application/json
      description: distribute segment to a percentage of users
      parameters:
      - description: segment name
        in: path
        name: segment
        required: true
        type: string
      - description: percentage of users to distribute (0-100)
        in: query
        name: percentage
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Distribute segment
      tags:
      - segments
  /users:
    get:
      consumes:
      - application/json
      description: get users and their segments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: List users
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Clear user segments
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Clear segments
      tags:
      - users
    get:
      consumes:
      - application/json
      description: show user's segments
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: show user
      tags:
      - users
  /users/{id}/{segment}:
    delete:
      consumes:
      - application/json
      description: delete segment
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      - description: segment's name
        in: path
        name: segment
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Delete segment
      tags:
      - users
    put:
      consumes:
      - application/json
      description: add new segment to user
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      - description: segment name
        in: path
        name: segment
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Add segment
      tags:
      - users
swagger: "2.0"
